BEGIN;

INSERT INTO
    public.productitems (
        id,
        product_name,
        description,
        product_category,
        vendor_id,
        auto_replenish,
        min_quantity,
        max_quantity,
        current_quantity,
        quantity_unit,
        barcode,
        qr_code,
        last_scanned,
        scan_history,
        expiration_date,
        updated_dt,
        draft_status,
        is_template
    )
VALUES
    (
        gen_random_uuid(),
        'Face Moisturizer',
        'Hydrating skin care product',
        'skin care',
        NULL,
        TRUE,
        NULL,
        NULL,
        1,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Acrylic Paint Set',
        'Set of 12 acrylic paints',
        'arts & crafts',
        NULL,
        TRUE,
        NULL,
        NULL,
        1,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Canned Beans',
        'Organic black beans',
        'pantry',
        NULL,
        TRUE,
        NULL,
        NULL,
        1,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Dish Soap',
        'Lemon scented dish soap',
        'kitchen supplies',
        NULL,
        TRUE,
        NULL,
        NULL,
        1,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Hammer',
        '16 oz claw hammer',
        'tools',
        NULL,
        TRUE,
        NULL,
        NULL,
        1,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Toothpaste',
        'Mint flavored toothpaste',
        'oral hygiene',
        NULL,
        TRUE,
        NULL,
        NULL,
        1,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Laundry Detergent',
        'Eco-friendly laundry detergent',
        'laundry supplies',
        NULL,
        TRUE,
        NULL,
        NULL,
        1,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Shampoo',
        'Moisturizing shampoo',
        'hair care',
        NULL,
        TRUE,
        NULL,
        NULL,
        1,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Paper Towels',
        'Absorbent paper towels',
        'kitchen supplies',
        NULL,
        TRUE,
        NULL,
        NULL,
        24,
        'roll',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Dish Soap',
        'Essential for handwashing dishes',
        'kitchen supplies',
        NULL,
        TRUE,
        1,
        3,
        2,
        'bottle',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Laundry Detergent',
        'Needed for washing clothes regularly',
        'laundry supplies',
        NULL,
        TRUE,
        1,
        2,
        1,
        'bottle',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Paper Towels',
        'Useful for cleaning spills and general messes',
        'kitchen supplies',
        NULL,
        TRUE,
        2,
        6,
        4,
        'roll',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Trash Bags',
        'Necessary for waste disposal',
        'kitchen supplies',
        NULL,
        TRUE,
        1,
        3,
        2,
        'box',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Sponges',
        'Used for scrubbing dishes and surfaces',
        'kitchen supplies',
        NULL,
        TRUE,
        3,
        10,
        5,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'All-Purpose Cleaner',
        'For cleaning various surfaces around the home',
        'kitchen supplies',
        NULL,
        TRUE,
        1,
        3,
        2,
        'bottle',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Window Cleaner',
        'Important for maintaining clean windows',
        'kitchen supplies',
        NULL,
        TRUE,
        1,
        2,
        1,
        'bottle',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Toilet Bowl Cleaner',
        'Keeps toilets clean and sanitary',
        'bathroom supplies',
        NULL,
        TRUE,
        1,
        2,
        1,
        'bottle',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Granite Cleaner',
        'Surface-specific cleaner for granite',
        'kitchen supplies',
        NULL,
        TRUE,
        1,
        2,
        1,
        'bottle',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Toothpaste',
        'A daily necessity for oral hygiene',
        'oral hygiene',
        NULL,
        TRUE,
        1,
        3,
        2,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Shampoo',
        'Regularly used for hair care',
        'hair care',
        NULL,
        TRUE,
        1,
        2,
        1,
        'bottle',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Conditioner',
        'Often used alongside shampoo',
        'hair care',
        NULL,
        TRUE,
        1,
        2,
        1,
        'bottle',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Body Wash',
        'Essential for personal hygiene',
        'personal hygiene',
        NULL,
        TRUE,
        1,
        2,
        1,
        'bottle',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Deodorant',
        'Important for daily freshness',
        'personal hygiene',
        NULL,
        TRUE,
        1,
        3,
        2,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Razors',
        'Needed for personal grooming',
        'personal hygiene',
        NULL,
        TRUE,
        2,
        10,
        5,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Aluminum Foil',
        'Used for cooking and food storage',
        'kitchen supplies',
        NULL,
        TRUE,
        1,
        2,
        1,
        'roll',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Plastic Wrap',
        'Handy for covering food items',
        'kitchen supplies',
        NULL,
        TRUE,
        1,
        2,
        1,
        'roll',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Freezer Bags',
        'Useful for storing food in the freezer',
        'kitchen supplies',
        NULL,
        TRUE,
        1,
        3,
        2,
        'box',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Sandwich Bags',
        'For packing lunches and snacks',
        'kitchen supplies',
        NULL,
        TRUE,
        1,
        3,
        2,
        'box',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Dishwasher Pods',
        'Necessary for running the dishwasher',
        'kitchen supplies',
        NULL,
        TRUE,
        10,
        50,
        30,
        'pcs',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    ),
    (
        gen_random_uuid(),
        'Toilet Paper',
        'A critical item in every household',
        'personal hygiene',
        NULL,
        TRUE,
        4,
        24,
        12,
        'roll',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'published',
        TRUE
    );

COMMIT;